insert into tour(tour_name,country,year_category,duration_tour,price) values ('Paris dream','France','winter tour','7','550');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Venecia weekend','Italy','summer tour','10','700');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Lunch in Bratislava','Slovakia','spring tour','3','150');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Date in Rome','Italy','autumn tour','7','650');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Sea fairytale','France','summer tour','5','750');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Western traditions','USA','spring tour','10','1550');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Meet Budapesht','Hungary','summer tour','3','250');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Football in Barcelona','Spain','winter tour','7','450');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Disneyland','France','winter tour','5','350');
insert into tour(tour_name,country,year_category,duration_tour,price) values ('Viena fairytale','Austria','spring tour','3','250');